### ISSUE TITLE
Can't import pipdated (decoding error on author's name)

### ISSUE THREAD

**Issue by tgrandje** [nschloe/pypi_update_checker#3]
Hello

_(I'm quite new to github, so it may not be the exact place to post this (sorry in that case...))_

When importing pipdated, I got an error due to encoding system :
`import pipdated `
```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import pipdated
  File "C:\Users\thomas.grandjean\Desktop\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\pipdated\__init__.py", line 15, in <module>
    from pipdated.helpers import *
  File "C:\Users\thomas.grandjean\Desktop\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\pipdated\helpers.py", line 34, in <module>
    _log_dir = appdirs.user_log_dir('pipdated', 'Nico SchlÃ¶mer')
  File "C:\Users\thomas.grandjean\Desktop\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\appdirs.py", line 351, in user_log_dir
    path = user_data_dir(appname, appauthor, version)
  File "C:\Users\thomas.grandjean\Desktop\WinPython-32bit-2.7.10.3\python-2.7.10\lib\site-packages\appdirs.py", line 84, in user_data_dir
    path = os.path.join(path, appauthor, appname)
  File "C:\Users\thomas.grandjean\Desktop\WinPython-32bit-2.7.10.3\python-2.7.10\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 9: ordinal not in range(128)
```
I had to replace _'Nico Schlömer'_ by _u'Nico Schlömer'_ in the helper.py file.
Regards
tgrandje

**Comment by nschloe** [comment]
Thanks for the report! Fixed now.
